version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
    - ./api/src:/api/src
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:app/src
    depends_on:
      - api
 
