version: "3"
services:
  api:
    env_file:
    - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
    - ./api/src:/api/src
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    depends_on:
      - api 
 
