name: test push action
on: push
jobs:
  build:
    defaults:
      run:
        working-directory: client
    name: build action
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run build in client
        working-directory: client
        run: |
          npm install
          npm run build 
          echo "completed build"
