name: test push action
on: push
jobs:
  build:
    name: build action
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3
      - name: Run build in client
        working-directory: client
        run: |
          npm run build 
          echo "completed build"
